name: Deploy GitHub Pages

on:
  push:
    branches:
      - main   # Chạy khi push lên branch main

# Đảm bảo chỉ có 1 job deploy chạy, hủy job cũ nếu có job mới
concurrency:
  group: github-pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Lấy code từ branch main
      - name: Checkout
        uses: actions/checkout@v3

      # Upload toàn bộ nội dung repo làm artifact (HTML/CSS/JS)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./   # Thư mục gốc repo

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Deploy artifact lên GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
