name: Deploy GitHub Pages

on:
  push:
    branches:
      - main   # Chạy khi push lên branch main

# Đảm bảo chỉ có 1 job deploy chạy, hủy job cũ nếu có job mới
concurrency:
  group: github-pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout source code
      - name: Checkout
        uses: actions/checkout@v4   # Phiên bản mới nhất

      # 2. Upload artifact (HTML/CSS/JS thuần)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3   # Phiên bản mới nhất
        with:
          path: ./   # Deploy toàn bộ nội dung repo

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 3. Deploy lên GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4   # Phiên bản mới nhất
